version: '3.8'

services:  
  universe-catalog-api:
    image: universe-catalog-api
    container_name: universe-catalog-api
    ports: 
      - 8000:8000
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure:10  
    depends_on: 
      - universe-catalog-db
  universe-catalog-db:
    image: mcr.microsoft.com/mssql/server
    user: root
    container_name: universe-catalog-db
    ports: 
      - 1401:1433
    environment: 
      SA_PASSWORD: "@Un1v3r53C4t4l0g"
      ACCEPT_EULA: "Y"
    volumes: 
      - universe-catalog-db-vol:/var/opt/mssql/data
volumes: 
  universe-catalog-db-vol: