version: "3.7"
services:
  db:
    container_name: "sql-container"
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - "./resources/sql:/var/opt/mssql/data"
    environment:
      SA_PASSWORD: "1SSCataloger@"
      ACCEPT_EULA: "Y"
